#! /usr/bin/env python

from pyplot import runtime
import math,copy,threading,time
import pam_O8O as pam


iteration = pam.last_iteration()    

pam.add_command(1,
                pam.Sign.ANTAGONIST,
                10000,
                iteration+600,
                pam.Mode.STACK)

for i in range(3):



    pam.add_command(0,
            pam.Sign.AGONIST,
            10000,
            iteration+100,
            pam.Mode.STACK)

    pam.add_command(0,
            pam.Sign.ANTAGONIST,
            16000,
            iteration+100,
            pam.Mode.STACK)

    pam.add_command(0,
            pam.Sign.AGONIST,
            16000,
            iteration+200,
            pam.Mode.STACK)

    pam.add_command(0,
            pam.Sign.ANTAGONIST,
            10000,
            iteration+200,
            pam.Mode.STACK)

    iteration+=200

pam.iteration_wait(iteration)

pam.status()

#    time.sleep(0.5)
