#! /usr/bin/env python

from pyplot import runtime
import math,copy,threading,time
import pam_O8O as pam
import sys

    
ids = [1];

def up_down(ids):

    for id in ids:

        for dof in range(4):
        
            pam.add_speed_command(id,
                                  dof,
                                  pam.Sign.AGONIST,
                                  20000,
                                  6000,
                                  pam.Mode.OVERWRITE)

            pam.add_speed_command(id,
                                  dof,
                                  pam.Sign.ANTAGONIST,
                                  20000,
                                  8000,
                                  pam.Mode.OVERWRITE)

            pam.add_speed_command(id,
                                  dof,
                                  pam.Sign.AGONIST,
                                  5000,
                                  8000,
                                  pam.Mode.STACK)

            pam.add_speed_command(id,
                                  dof,
                                  pam.Sign.ANTAGONIST,
                                  5000,
                                  6000,
                                  pam.Mode.STACK)

        pam.pulse(id)
            
up_down(ids)




