#! /usr/bin/env python

from pyplot import runtime
import math,copy,threading,time
import pam_O8O as pam
import sys

    
ids = [1];
#pam.set_simulation()
#pam.pulse()


def up_down_motion(ids):

    iterations = {id:pam.last_iteration(id)
                  for id in ids}
    
    for i in range(3):

        for id in ids:

            iteration = iterations[id]
            
            for dof in range(4):

                pam.add_command(id,
                                dof,
                                pam.Sign.AGONIST,
                                20000,
                                iteration+500,
                                pam.Mode.OVERWRITE)

                pam.add_command(id,
                                dof,
                                pam.Sign.AGONIST,
                                10000,
                                iteration+1000,
                                pam.Mode.STACK)

                pam.add_command(id,
                                dof,
                                pam.Sign.ANTAGONIST,
                                10000,
                                iteration+500,
                                pam.Mode.OVERWRITE)

                pam.add_command(id,
                                dof,
                                pam.Sign.ANTAGONIST,
                                20000,
                                iteration+1000,
                                pam.Mode.STACK)


                pam.add_command(id,
                                dof,
                                pam.Sign.AGONIST,
                                5000,
                                iteration+2000,
                                pam.Mode.STACK)

                pam.add_command(id,
                                dof,
                                pam.Sign.ANTAGONIST,
                                5000,
                                iteration+2000,
                                pam.Mode.STACK)


        for id in ids:
            pam.pulse(id)
        iterations= {k:v+1000 for k,v in iterations.items()}
        for id,iteration in iterations.items():
            pam.iteration_wait(id,iteration)

    

up_down_motion(ids)




