#! /usr/bin/env python3

from pyplot import runtime
import math,copy,threading,time
import pam_O8O as pam
import sys

    
ids = [1];

def up(ids):

    for id in ids:

        for dof in range(4):
        
            pam.add_speed_command(id,
                                  dof,
                                  pam.Sign.AGONIST,
                                  20000,
                                  9000,
                                  pam.Mode.OVERWRITE)

            pam.add_speed_command(id,
                                  dof,
                                  pam.Sign.ANTAGONIST,
                                  20000,
                                  12000,
                                  pam.Mode.OVERWRITE)

        pam.wait_for_completion(id)

            
def down(ids):

    for id in ids:

        for dof in range(4):
    
            pam.add_speed_command(id,
                                  dof,
                                  pam.Sign.AGONIST,
                                  5000,
                                  12000,
                                  pam.Mode.STACK)

            pam.add_speed_command(id,
                                  dof,
                                  pam.Sign.ANTAGONIST,
                                  5000,
                                  9000,
                                  pam.Mode.STACK)
            
        pam.wait_for_completion(id)
        
            
up(ids)
down(ids)




